---
abstract: 'Perl interface to the Phat widget collection'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Gtk2-Phat
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
requires:
  Gtk2: 0
  perl: 5.8.0
version: 0.04
